### ISSUE TITLE
Feature Request - show host disk size remaining

### ISSUE THREAD

**Issue by lgaudreau** [amerkurev/doku#1]
I just tried out Doku on my Raspberrry Pi using USB boot and it worked great - including the logs!

One thing I was hoping to see was how much space left I have on the Pi's disk (or any host running Docker).

Is this something that could be added?

**Comment by amerkurev** [comment]
Thanks for the good idea, @lgaudreau !  I was thinking the same thing. I'll try to do that, but it's hard.

**Comment by lgaudreau** [comment]
Thanks!  Looks great.
