### ISSUE TITLE
Doku uses ~ 60% of both cores on radeon R5 A9-9420

### ISSUE THREAD

**Issue by kavemang** [amerkurev/doku#10]
Hi, I'm finding Doku seems to use about 60% of both cores on the machine im trying it from, core is a radeon R5 A9-9420

**Comment by lazerleif** [comment]
I have the same issue, Dockerd uses 100%+ when i start the doku docker. I have a elitedesk 800 G2 with a Intel Core i5 6600T.

**Comment by cpuks** [comment]
Same here on 8th gen i5

**Comment by kavemang** [comment]
Thats hilarious because the cpus you guys are using are equivalent to ateast 3 of mine, until i saw this i suspected my cpu was just to weak to support whatever method doku is using

Totally forgot about this project till now, i was never able it make it work practially

**Comment by cpuks** [comment]
Well it's not 100% of all cores but according to UPS using just this one docker on top of my idle which is 50-54 W - consumption jumps to 70-74 W and extra 30-35% per core. Project is really nice I mean visualisation wise but it should eat such amount of energy.

**Comment by skywurz** [comment]
Intel® Core™ i7-7820X CPU @ 3.60GHz on unRaid same issue burns a lot of CPU

**Comment by Portagoras** [comment]
Similar issue. Moves my CPU usage from 1% to 10-20% depending if it has been running a while. (R7 1700X, Unraid)
