### ISSUE TITLE
client version 1.41 is too new

### ISSUE THREAD

**Issue by yanggongwang** [amerkurev/doku#8]
time="2022-07-20T02:33:08Z" level=error msg="failed to get the list of containers" err="Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"
time="2022-07-20T02:33:08Z" level=error msg="poll: docker version" err="failed to execute request: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"
time="2022-07-20T02:33:08Z" level=error msg="poll: docker container list" err="failed to execute request: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"
time="2022-07-20T02:33:08Z" level=error msg="poll: docker disk usage" err="failed to execute request: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"
time="2022-07-20T02:33:08Z" level=error msg="poll: docker log size" err="failed to execute request: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"
time="2022-07-20T02:33:08Z" level=error msg="failed to listen to docker events" err="Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"
time="2022-07-20T02:34:08Z" level=error msg="failed to listen to docker events" err="Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40"

**Comment by eskiiom** [comment]
Hello

same issue here with 1.41

`time="2022-08-07T17:25:36Z" level=error msg="failed to listen to docker events" err="Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39"`
